const API='https://vgnmkikduqpiarxjbqpg.supabase.co/functions/v1/storefront-api';
let products=[],categories=[],variants=[],razorpayEnabled=false;let cart=JSON.parse(localStorage.getItem('milletMitraCart')||'[]');let activeCategory='all';
const $=id=>document.getElementById(id);const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0);
function saveCart(){localStorage.setItem('milletMitraCart',JSON.stringify(cart));renderCart()}
function renderCart(){$('cartCount').textContent=cart.reduce((n,i)=>n+i.quantity,0);$('cartItems').innerHTML=cart.length?cart.map((i,n)=>`<div class="cart-line"><div><strong>${i.name}</strong><small>${i.label||`${money(i.price)} × ${i.quantity}`}</small><b>${money(i.price*i.quantity)}</b></div><button data-remove="${n}">×</button></div>`).join(''):'<div class="empty">Your cart is waiting for something good.</div>';$('cartTotal').textContent=money(cart.reduce((s,i)=>s+i.price*i.quantity,0))}
function openCart(){$('cartDrawer').classList.add('open');$('overlay').classList.add('show')};function closeCart(){$('cartDrawer').classList.remove('open');$('overlay').classList.remove('show')}
$('cartButton').onclick=openCart;$('closeCart').onclick=closeCart;$('overlay').onclick=closeCart;$('cartItems').onclick=e=>{const b=e.target.closest('[data-remove]');if(!b)return;cart.splice(Number(b.dataset.remove),1);saveCart()};
function renderCategories(){const all=[{id:'all',name:'All products'},...categories];$('categoryBar').innerHTML=all.map(c=>`<button class="${activeCategory===c.id?'active':''}" data-category="${c.id}">${c.name}</button>`).join('');$('categoryBar').querySelectorAll('button').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;renderCategories();renderProducts()})}
function productVariants(p){return variants.filter(v=>v.product_id===p.id)}
function renderProducts(){const shown=activeCategory==='all'?products:products.filter(p=>p.category_id===activeCategory);if(!shown.length){$('productGrid').innerHTML='<div class="empty">Our first collection is being prepared. Products will appear here soon.</div>';return}$('productGrid').innerHTML=shown.map(p=>{const vs=productVariants(p);const hasVariants=vs.length>0;const first=vs[0];const displayPrice=first?first.price:p.price;return `<article class="product-card"><div class="product-image">${p.name.slice(0,1)}</div><div class="product-info"><h3>${p.name}</h3><p>${p.short_description||'Thoughtfully selected for everyday living.'}</p>${hasVariants?`<label class="weight-label">Choose pack size<select class="weight-select" data-product="${p.id}">${vs.map(v=>`<option value="${v.id}" data-price="${v.price}" data-label="${v.label}">${v.label}</option>`).join('')}</select></label>`:''}<div class="price-row"><span class="price" data-price-for="${p.id}">${money(displayPrice)}</span><button class="add" data-add="${p.id}">+</button></div></div></article>`}).join('');
$('productGrid').querySelectorAll('.weight-select').forEach(s=>s.onchange=()=>{const v=variants.find(x=>x.id===s.value);if(v)document.querySelector(`[data-price-for="${s.dataset.product}"]`).textContent=money(v.price)});
$('productGrid').onclick=e=>{const b=e.target.closest('[data-add]');if(!b)return;const p=products.find(x=>x.id===b.dataset.add);const s=document.querySelector(`[data-product="${p.id}"]`);const v=s?variants.find(x=>x.id===s.value):null;const price=v?v.price:p.price;const key=v?.id||p.id;const old=cart.find(x=>(x.variant_id||x.product_id)===key);if(old)old.quantity++;else cart.push({product_id:p.id,variant_id:v?.id||null,name:p.name,label:v?.label||p.unit,price,quantity:1});saveCart();openCart()}}
async function loadCatalog(){try{const r=await fetch(API);const body=await r.json();if(!r.ok)throw new Error(body.error);categories=body.categories||[];products=body.products||[];variants=body.variants||[];razorpayEnabled=Boolean(body.razorpay_enabled);renderCategories();renderProducts();$('paymentAvailability').textContent=razorpayEnabled?'Online payments are ready for Razorpay Test/Live Mode.':'Online payments are not configured yet; COD is available.';if(!razorpayEnabled){document.querySelector('input[value="razorpay"]').disabled=true;document.querySelector('input[value="cod"]').checked=true;$('placeOrderButton').textContent='Place COD order'}}catch(e){console.error(e);$('productGrid').innerHTML='<div class="empty">Catalogue temporarily unavailable.</div>'}}
$('checkoutButton').onclick=()=>{if(cart.length){closeCart();$('checkoutDialog').showModal()}};
function itemsPayload(){return cart.map(i=>({product_id:i.product_id,variant_id:i.variant_id||undefined,quantity:i.quantity}))}
async function placeCod(values,msg){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cod_order',...values,items:itemsPayload()})});const body=await r.json();if(!r.ok)throw new Error(body.error||'Unable to place order');return body.order}
async function startRazorpay(values,msg){const create=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create_payment_order',items:itemsPayload()})});const paymentOrder=await create.json();if(!create.ok)throw new Error(paymentOrder.error||'Unable to start payment');if(!window.Razorpay)throw new Error('Payment checkout could not load. Please try again.');return await new Promise((resolve,reject)=>{const rzp=new Razorpay({key:paymentOrder.key_id,amount:paymentOrder.amount,currency:paymentOrder.currency,name:'Millet Mitra',description:'Millet Mitra order',order_id:paymentOrder.razorpay_order_id,prefill:{name:values.customer_name,email:values.customer_email,contact:values.customer_phone},theme:{color:'#5b6f36'},handler:async response=>{try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'finalize_payment',...values,items:itemsPayload(),amount:paymentOrder.amount,razorpay_order_id:response.razorpay_order_id,razorpay_payment_id:response.razorpay_payment_id,razorpay_signature:response.razorpay_signature})});const body=await r.json();if(!r.ok)throw new Error(body.error||'Payment verification failed');resolve(body.order)}catch(err){reject(err)}},modal:{ondismiss:()=>reject(new Error('Payment window closed.'))}});rzp.open()})}
$('checkoutForm').onsubmit=async e=>{e.preventDefault();const msg=$('checkoutMessage'),button=$('placeOrderButton'),values=Object.fromEntries(new FormData(e.currentTarget).entries());msg.textContent='Processing…';button.disabled=true;try{const order=values.payment_method==='razorpay'&&razorpayEnabled?await startRazorpay(values,msg):await placeCod(values,msg);const number=order?.order_number||'';cart=[];saveCart();e.currentTarget.reset();$('checkoutDialog').close();alert(`Thank you! Your order ${number} has been placed.`)}catch(err){msg.textContent=err.message}finally{button.disabled=false}}
renderCart();loadCatalog();
