const API='https://vgnmkikduqpiarxjbqpg.supabase.co/functions/v1/storefront-api';
let products=[],categories=[],variants=[],razorpayEnabled=false,catalogueFallback=false;let cart=JSON.parse(localStorage.getItem('milletMitraCart')||'[]');let activeCategory='all';
const $=id=>document.getElementById(id);const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0);
const starterCategories=[
{id:'grains',name:'Millet Grains'},
{id:'snacks',name:'Millet Snacks'},
{id:'flours',name:'Millet Flours'}
];
const starterProducts=[
{id:'starter-foxtail',category_id:'grains',name:'Foxtail Millet (Korra)',slug:'foxtail-millet',short_description:'Clean, everyday foxtail millet for wholesome home cooking.',price:95,unit:'500 g',featured:true},
{id:'starter-little',category_id:'grains',name:'Little Millet (Samalu)',slug:'little-millet',short_description:'A versatile traditional millet for everyday meals.',price:90,unit:'500 g',featured:true},
{id:'starter-kodo',category_id:'grains',name:'Kodo Millet (Arikelu)',slug:'kodo-millet',short_description:'A naturally hearty millet for rice-style meals.',price:85,unit:'500 g',featured:false},
{id:'starter-barnyard',category_id:'grains',name:'Barnyard Millet (Udalu)',slug:'barnyard-millet',short_description:'Light and versatile millet for everyday recipes.',price:95,unit:'500 g',featured:false},
{id:'starter-bajra',category_id:'grains',name:'Pearl Millet (Bajra)',slug:'pearl-millet',short_description:'Traditional bajra with a rich, earthy flavour.',price:70,unit:'500 g',featured:false},
{id:'starter-ragi',category_id:'flours',name:'Finger Millet (Ragi) Flour',slug:'ragi-flour',short_description:'Fine ragi flour for dosa, porridge, rotis and more.',price:75,unit:'500 g',featured:true},
{id:'starter-jowar',category_id:'flours',name:'Jowar (Sorghum) Flour',slug:'jowar-flour',short_description:'Fresh jowar flour for rotis, dosa and traditional recipes.',price:70,unit:'500 g',featured:false},
{id:'starter-ragi-cookies',category_id:'snacks',name:'Ragi Millet Cookies',slug:'ragi-cookies',short_description:'A popular millet snack option for tea-time.',price:100,unit:'100 g',featured:true},
{id:'starter-murukku',category_id:'snacks',name:'Millet Murukku',slug:'millet-murukku',short_description:'Crispy traditional-style millet murukku.',price:120,unit:'100 g',featured:true},
{id:'starter-mixture',category_id:'snacks',name:'Millet Mixture',slug:'millet-mixture',short_description:'Crunchy millet-based savoury snack mix.',price:120,unit:'100 g',featured:true},
{id:'starter-laddu',category_id:'snacks',name:'Ragi Laddu',slug:'ragi-laddu',short_description:'Traditional ragi laddu made for a wholesome sweet bite.',price:150,unit:'150 g',featured:false},
{id:'starter-chikkies',category_id:'snacks',name:'Millet Chikkies',slug:'millet-chikkies',short_description:'Crunchy millet and jaggery-style snack.',price:90,unit:'150 g',featured:false}
];
function saveCart(){localStorage.setItem('milletMitraCart',JSON.stringify(cart));renderCart()}
function renderCart(){$('cartCount').textContent=cart.reduce((n,i)=>n+i.quantity,0);$('cartItems').innerHTML=cart.length?cart.map((i,n)=>`<div class="cart-line"><div><strong>${i.name}</strong><small>${i.label||`${money(i.price)} × ${i.quantity}`}</small><b>${money(i.price*i.quantity)}</b></div><button data-remove="${n}">×</button></div>`).join(''):'<div class="empty">Your cart is waiting for something good.</div>';$('cartTotal').textContent=money(cart.reduce((s,i)=>s+i.price*i.quantity,0))}
function openCart(){$('cartDrawer').classList.add('open');$('overlay').classList.add('show')};function closeCart(){$('cartDrawer').classList.remove('open');$('overlay').classList.remove('show')}
$('cartButton').onclick=openCart;$('closeCart').onclick=closeCart;$('overlay').onclick=closeCart;$('cartItems').onclick=e=>{const b=e.target.closest('[data-remove]');if(!b)return;cart.splice(Number(b.dataset.remove),1);saveCart()};
function renderCategories(){const all=[{id:'all',name:'All products'},...categories];$('categoryBar').innerHTML=all.map(c=>`<button class="${activeCategory===c.id?'active':''}" data-category="${c.id}">${c.name}</button>`).join('');$('categoryBar').querySelectorAll('button').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;renderCategories();renderProducts()})}
function productVariants(p){return variants.filter(v=>v.product_id===p.id)}
function renderProducts(){const shown=activeCategory==='all'?products:products.filter(p=>p.category_id===activeCategory);if(!shown.length){$('productGrid').innerHTML='<div class="empty">Our first collection is being prepared. Products will appear here soon.</div>';return}$('productGrid').innerHTML=shown.map(p=>{const vs=productVariants(p);const hasVariants=vs.length>0;const first=vs[0];const displayPrice=first?first.price:p.price;const fallbackCard=catalogueFallback?'<span class="catalogue-badge">Collection preview</span>':'';return `<article class="product-card"><div class="product-image">${p.name.slice(0,1)}</div><div class="product-info"><h3>${p.name}</h3><p>${p.short_description||'Thoughtfully selected for everyday living.'}</p>${hasVariants?`<label class="weight-label">Choose pack size<select class="weight-select" data-product="${p.id}">${vs.map(v=>`<option value="${v.id}" data-price="${v.price}" data-label="${v.label}">${v.label}</option>`).join('')}</select></label>`:''}<div class="price-row"><span class="price" data-price-for="${p.id}">${money(displayPrice)}</span>${fallbackCard||'<button class="add" data-add="'+p.id+'">+</button>'}</div></div></article>`}).join('');
$('productGrid').querySelectorAll('.weight-select').forEach(s=>s.onchange=()=>{const v=variants.find(x=>x.id===s.value);if(v)document.querySelector(`[data-price-for="${s.dataset.product}"]`).textContent=money(v.price)});
$('productGrid').onclick=e=>{const b=e.target.closest('[data-add]');if(!b)return;const p=products.find(x=>x.id===b.dataset.add);const s=document.querySelector(`[data-product="${p.id}"]`);const v=s?variants.find(x=>x.id===s.value):null;const price=v?v.price:p.price;const key=v?.id||p.id;const old=cart.find(x=>(x.variant_id||x.product_id)===key);if(old)old.quantity++;else cart.push({product_id:p.id,variant_id:v?.id||null,name:p.name,label:v?.label||p.unit,price,quantity:1});saveCart();openCart()}}
function useStarterCatalogue(){catalogueFallback=true;categories=starterCategories;products=starterProducts;variants=[];razorpayEnabled=false;renderCategories();renderProducts();$('paymentAvailability').textContent='Online payments will be enabled after the live catalogue and Razorpay configuration are completed.';document.querySelector('input[value="razorpay"]').disabled=true;document.querySelector('input[value="cod"]').checked=true;$('placeOrderButton').textContent='Place COD order'}
async function loadCatalog(){try{const r=await fetch(API,{cache:'no-store'});const body=await r.json();if(!r.ok)throw new Error(body.error||'Catalogue API error');categories=body.categories||[];products=body.products||[];variants=body.variants||[];razorpayEnabled=Boolean(body.razorpay_enabled);if(!products.length){useStarterCatalogue();return}renderCategories();renderProducts();$('paymentAvailability').textContent=razorpayEnabled?'Online payments are ready for Razorpay Test/Live Mode.':'Online payments are not configured yet; COD is available.';if(!razorpayEnabled){document.querySelector('input[value="razorpay"]').disabled=true;document.querySelector('input[value="cod"]').checked=true;$('placeOrderButton').textContent='Place COD order'}}catch(e){console.error(e);useStarterCatalogue()}}
$('checkoutButton').onclick=()=>{if(cart.length){closeCart();$('checkoutDialog').showModal()}};
function itemsPayload(){return cart.map(i=>({product_id:i.product_id,variant_id:i.variant_id||undefined,quantity:i.quantity}))}
async function placeCod(values){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'cod_order',...values,items:itemsPayload()})});const body=await r.json();if(!r.ok)throw new Error(body.error||'Unable to place order');return body.order}
async function startRazorpay(values){const create=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create_payment_order',items:itemsPayload()})});const paymentOrder=await create.json();if(!create.ok)throw new Error(paymentOrder.error||'Unable to start payment');if(!window.Razorpay)throw new Error('Payment checkout could not load. Please try again.');return await new Promise((resolve,reject)=>{const rzp=new Razorpay({key:paymentOrder.key_id,amount:paymentOrder.amount,currency:paymentOrder.currency,name:'Millet Mitra',description:'Millet Mitra order',order_id:paymentOrder.razorpay_order_id,prefill:{name:values.customer_name,email:values.customer_email,contact:values.customer_phone},theme:{color:'#5b6f36'},handler:async response=>{try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'finalize_payment',...values,items:itemsPayload(),amount:paymentOrder.amount,razorpay_order_id:response.razorpay_order_id,razorpay_payment_id:response.razorpay_payment_id,razorpay_signature:response.razorpay_signature})});const body=await r.json();if(!r.ok)throw new Error(body.error||'Payment verification failed');resolve(body.order)}catch(err){reject(err)}},modal:{ondismiss:()=>reject(new Error('Payment window closed.'))}});rzp.open()})}
$('checkoutForm').onsubmit=async e=>{e.preventDefault();if(catalogueFallback){$('checkoutMessage').textContent='Our starter collection is visible now. Checkout will be enabled as soon as the live product catalogue is connected.';return}const button=$('placeOrderButton'),values=Object.fromEntries(new FormData(e.currentTarget).entries());$('checkoutMessage').textContent='Processing…';button.disabled=true;try{const order=values.payment_method==='razorpay'&&razorpayEnabled?await startRazorpay(values):await placeCod(values);const number=order?.order_number||'';cart=[];saveCart();e.currentTarget.reset();$('checkoutDialog').close();alert(`Thank you! Your order ${number} has been placed.`)}catch(err){$('checkoutMessage').textContent=err.message}finally{button.disabled=false}}
renderCart();loadCatalog();