const API='https://vgnmkikduqpiarxjbqpg.supabase.co/functions/v1/storefront-api';
let products=[];let categories=[];let cart=JSON.parse(localStorage.getItem('milletMitraCart')||'[]');let activeCategory='all';
const WEIGHTS=[0.5,1,1.5,2,2.5,3,3.5,4,4.5,5];
const $=id=>document.getElementById(id);const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v||0);
function saveCart(){localStorage.setItem('milletMitraCart',JSON.stringify(cart));renderCart()}
function renderCart(){ $('cartCount').textContent=cart.reduce((n,i)=>n+i.quantity,0);$('cartItems').innerHTML=cart.length?cart.map((i,n)=>`<div class="cart-line"><div><strong>${i.name}</strong><small>${i.weight_kg?`${i.weight_kg} kg`: `${money(i.price)} × ${i.quantity}`}</small><b>${money(i.price*i.quantity)}</b></div><button data-remove="${n}">×</button></div>`).join(''):'<div class="empty">Your cart is waiting for something good.</div>';$('cartTotal').textContent=money(cart.reduce((s,i)=>s+i.price*i.quantity,0))}
function openCart(){$('cartDrawer').classList.add('open');$('overlay').classList.add('show')};function closeCart(){$('cartDrawer').classList.remove('open');$('overlay').classList.remove('show')}
$('cartButton').onclick=openCart;$('closeCart').onclick=closeCart;$('overlay').onclick=closeCart;
$('cartItems').onclick=e=>{const b=e.target.closest('[data-remove]');if(!b)return;cart.splice(Number(b.dataset.remove),1);saveCart()};
function renderCategories(){const all=[{id:'all',name:'All products'},...categories];$('categoryBar').innerHTML=all.map(c=>`<button class="${activeCategory===c.id?'active':''}" data-category="${c.id}">${c.name}</button>`).join('');$('categoryBar').querySelectorAll('button').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;renderCategories();renderProducts()})}
function isWeightProduct(p){return p.unit?.toLowerCase().includes('kg')&&!/cookie|puff|chip|murukku|mixture|laddu|khakhra|nippattu|chakli/i.test(p.name)}
function renderProducts(){const shown=activeCategory==='all'?products:products.filter(p=>p.category_id===activeCategory);if(!shown.length){$('productGrid').innerHTML='<div class="empty">Our first collection is being prepared. Products will appear here soon.</div>';return}$('productGrid').innerHTML=shown.map(p=>{const weightProduct=isWeightProduct(p);return `<article class="product-card"><div class="product-image">${p.name.slice(0,1)}</div><div class="product-info"><h3>${p.name}</h3><p>${p.short_description||'Thoughtfully selected for everyday living.'}</p>${weightProduct?`<label class="weight-label">Choose quantity<select class="weight-select" data-weight-for="${p.id}">${WEIGHTS.map(w=>`<option value="${w}">${w} kg</option>`).join('')}</select></label>`:''}<div class="price-row"><span class="price" data-price-for="${p.id}">${money(weightProduct?p.price*0.5:p.price)}${weightProduct?' <small>/ 0.5 kg</small>':''}</span><button class="add" data-add="${p.id}">+</button></div></div></article>`}).join('');
$('productGrid').querySelectorAll('.weight-select').forEach(s=>s.onchange=()=>{const p=products.find(x=>x.id===s.dataset.weightFor);document.querySelector(`[data-price-for="${p.id}"]`).innerHTML=`${money(p.price*Number(s.value))} <small>/ ${s.value} kg</small>`});
$('productGrid').onclick=e=>{const b=e.target.closest('[data-add]');if(!b)return;const p=products.find(x=>x.id===b.dataset.add);const select=document.querySelector(`[data-weight-for="${p.id}"]`);const weight=select?Number(select.value):null;const old=cart.find(x=>x.product_id===p.id&&x.weight_kg===weight);if(old)old.quantity++;else cart.push({product_id:p.id,name:p.name,price:weight?p.price*weight:p.price,quantity:1,weight_kg:weight});saveCart();openCart()}}
async function loadCatalog(){try{const r=await fetch(API);const body=await r.json();if(!r.ok)throw new Error(body.error);categories=body.categories||[];products=body.products||[];renderCategories();renderProducts()}catch(e){console.error(e);$('productGrid').innerHTML='<div class="empty">Catalogue temporarily unavailable.</div>'}}
$('checkoutButton').onclick=()=>{if(cart.length){closeCart();$('checkoutDialog').showModal()}};
$('checkoutForm').onsubmit=async e=>{e.preventDefault();const msg=$('checkoutMessage'),values=Object.fromEntries(new FormData(e.currentTarget).entries());msg.textContent='Placing your order…';try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,items:cart.map(i=>({product_id:i.product_id,quantity:i.weight_kg?i.weight_kg*2:i.quantity}))})});const body=await r.json();if(!r.ok)throw new Error(body.error||'Unable to place order');const number=body.order?.order_number||'';cart=[];saveCart();e.currentTarget.reset();$('checkoutDialog').close();alert(`Thank you! Your order ${number} has been placed.`)}catch(err){msg.textContent=err.message}}
renderCart();loadCatalog();
